[project]
name = "fastapi-htmx-paint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.116.1",
    "pillow>=11.3.0",
    "ruff>=0.12.10",
    "scikit-learn>=1.7.1",
]
